apiVersion: v1
kind: Pod
metadata:
  name: weather-backend-pod
  labels:
    app.kubernetes.io/name: weather-backend
spec:
  containers:
    - name: weather-backend-pod
      image: congenial-eureka/weather-backend:v1
      # imagePullPolicy: Always
      ports:
        - containerPort: 3000
          name: http-api-svc
      env:
        - name: NESTJS_WEATHER_API_KEY
          value: "60e6d02e15a84ad2bfb154448241811"
        - name: NESTJS_MONGODB
          value: "mongodb://mongod-svc.default.svc.cluster.local/weather"
---
# weather-backend-svc.default.svc.cluster.local/romeo-please-call-me
apiVersion: v1
kind: Service
metadata:
  name: weather-backend-svc
spec:
  selector:
    app.kubernetes.io/name: weather-backend
  ports:
    - name: http
      port: 3000
      targetPort: http-api-svc
  type: LoadBalancer
