apiVersion: v1
kind: Pod
metadata:
  name: mongod-pod
  labels:
    app.kubernetes.io/name: mongod
spec:
  containers:
    - name: mongod
      image: mongo:latest
      ports:
        - containerPort: 27017
          name: mongodb
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      persistentVolumeClaim:
        claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongod-svc
spec:
  selector:
    app.kubernetes.io/name: mongod
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
  type: LoadBalancer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-sc
provisioner: docker.io/hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: docker-sc # hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/austonpramodh/Desktop/projects/congenial-eureka/mongodb-data" # Host path on MacOS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: docker-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
